
# autogenerated setup.py on ymd_hm-2014-09-02_14-35 for /home/joncrall/srcdistro/yael_v401
from __future__ import absolute_import, division, print_function
import setuptools
#from utool import util_setup

INSTALL_REQUIRES = [
]

if __name__ == '__main__':
    setuptools.setup(
        name='yael_v401',
        packages=['yael'],
        #packages=util_setup.find_packages(),
        #version='0.0.0.autogen',
        #description='short description',
        #url='',
        #ext_modules=util_setup.find_ext_modules(),
        #cmdclass=util_setup.get_cmdclass(),
        #author=''
        #author_email='',
        #keywords='',
        #install_requires=INSTALL_REQUIRES,
        package_data={},
        scripts=[
        ],
        classifiers=[],
    )
